name: Build Kali Linux ISO

on:
  push:
    branches:
      - main

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl wget

      - name: Clone Kali Linux repository
        run: |
          git clone https://github.com/Spijkervet/Kali-Linux-Live.git
          cd Kali-Linux-Live

      - name: Configure Kali Linux build
        run: |
          # Customize Kali Linux build (e.g., add packages, change shell)
          echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee /etc/apt/sources.list
          sudo apt update
          sudo apt install -y kali-linux-default
          sudo apt install -y $(curl -s https://raw.githubusercontent.com/maaaaz/dotfiles/master/debian_ubuntu_packages.txt)
          sudo apt install -y $(curl -s https://raw.githubusercontent.com/maaaaz/dotfiles/master/kali_missing_packages.txt)
          sudo apt install -y sysmon procdump
          sudo apt install -y escobar
          sudo chsh -s /bin/bash
          sudo echo "set nocompatible" >> ~/.vimrc

      - name: Build Kali Linux ISO
        run: |
          # Build Kali Linux ISO using the official custom ISO method
          sudo ./build.sh

      - name: Upload ISO to release
        uses: actions/upload-artifact@v2
        with:
          name: kali-linux-iso
          path: kali-linux-*.iso

      - name: Create release
        uses: actions/create-release@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Kali Linux Custom ISO
          release_body: |
            This is a custom Kali Linux ISO built using GitHub Actions.
            It includes additional packages and customizations.
          draft: false
          prerelease: false

      - name: Upload ISO to release
        uses: actions/upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ steps.create-release.outputs.release_id }}
          file: kali-linux-*.iso
          name: kali-linux-iso
