name: Build Kali Linux ISO and Upload to Release

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential devscripts debhelper

      - name: Clone Kali Linux repository
        run: |
          git clone https://gitlab.com/kalilinux/build-scripts.git
          cd build-scripts

      - name: Build Kali Linux ISO
        run: |
         ./build.sh --variant kali-linux --arch amd64 --iso

      - name: Upload ISO to release
        uses: actions/upload-artifact@v2
        with:
          name: kali-linux-iso
          path: kali-linux-*.iso

      - name: Create release
        uses: actions/create-release@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Kali Linux ISO
          release_body: |
            This is an automated release of Kali Linux ISO.
          draft: false
          prerelease: false

      - name: Upload ISO to release
        uses: actions/upload-release-asset@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_id: ${{ steps.create-release.outputs.release_id }}
          file: kali-linux-*.iso
          file_name: kali-linux-iso
